export const jacketList = [
	{
		id: "1",
		name: "Jacket 1",
		jacketImg: "../images/products/jacket1.webp",
		gender: "male",
		price: 2600,
		description: "",
		bestSeller: false,
	},
	{
		id: "2",
		name: "Jacket 2",
		jacketImg: "../images/products/jacket2.webp",
		gender: "female",
		price: 1800,
		description: "",
		bestSeller: true,
	},
	{
		id: "3",
		name: "Jacket 3",
		jacketImg: "../images/products/jacket3.webp",
		gender: "female",
		price: 2900,
		description: "",
		bestSeller: false,
	},
	{
		id: "4",
		name: "Jacket 4",
		jacketImg: "../images/products/jacket4.webp",
		gender: "male",
		price: 1750,
		description: "",
		bestSeller: true,
	},
	{
		id: "5",
		name: "Jacket 5",
		jacketImg: "../images/products/jacket5.webp",
		gender: "female",
		price: 2200,
		description: "",
		bestSeller: false,
	},
	{
		id: "6",
		name: "Jacket 6",
		jacketImg: "../images/products/jacket6.webp",
		gender: "male",
		price: 3800,
		description: "",
		bestSeller: true,
	},
	{
		id: "7",
		name: "Jacket 7",
		jacketImg: "../images/products/jacket7.webp",
		gender: "female",
		price: 1400,
		description: "",
		bestSeller: false,
	},
	{
		id: "8",
		name: "Jacket 8",
		jacketImg: "../images/products/jacket8.webp",
		gender: "male",
		price: 2180,
		description: "",
		bestSeller: false,
	},
	{
		id: "9",
		name: "Jacket 1",
		jacketImg: "../images/products/jacket1.webp",
		gender: "male",
		price: 2600,
		description: "",
		bestSeller: false,
	},
	{
		id: "10",
		name: "Jacket 2",
		jacketImg: "../images/products/jacket2.webp",
		gender: "female",
		price: 1800,
		description: "",
		bestSeller: false,
	},
	{
		id: "11",
		name: "Jacket 3",
		jacketImg: "../images/products/jacket3.webp",
		gender: "female",
		price: 2900,
		description: "",
		bestSeller: false,
	},
	{
		id: "12",
		name: "Jacket 4",
		jacketImg: "../images/products/jacket4.webp",
		gender: "male",
		price: 1750,
		description: "",
		bestSeller: false,
	},
	{
		id: "13",
		name: "Jacket 5",
		jacketImg: "../images/products/jacket5.webp",
		gender: "female",
		price: 2200,
		description: "",
		bestSeller: false,
	},
	{
		id: "14",
		name: "Jacket 6",
		jacketImg: "../images/products/jacket6.webp",
		gender: "male",
		price: 3800,
		description: "",
		bestSeller: false,
	},
	{
		id: "15",
		name: "Jacket 7",
		jacketImg: "../images/products/jacket7.webp",
		gender: "female",
		price: 1400,
		description: "",
		bestSeller: false,
	},
	{
		id: "16",
		name: "Jacket 8",
		jacketImg: "../images/products/jacket8.webp",
		gender: "male",
		price: 2180,
		description: "",
		bestSeller: true,
	},
];
